### ISSUE TITLE
Handle both Private and Public repos

### ISSUE THREAD

**Issue by ronaldtse** [actions-mn/build-and-publish#1]
I suppose that for both Private and Public repos we can upload to GH pages. Not sure if we need to do more.

**Comment by ronaldtse** [comment]
The action isn't working, it does not install Metanorma or utilize the Metanorma docker container:

https://github.com/metanorma/scc-ab-docs/actions/runs/3484532689/jobs/5829188481

**Comment by CAMOBAP** [comment]
@ronaldtse  Yep, this is how it was designed.

The idea is to set up metanorma first with `container: metanorma/metanomra` or with `actions-mn/setup`. Like we did in https://github.com/metanorma/S-102-Product-Specification/blob/main/.github/workflows/generate.yml

Moreover we also have a separate `setup-flavors` action so it's definitely make sense to separate setup step from build

**Comment by ronaldtse** [comment]
@CAMOBAP thanks. Can you provide documentation in the README? I had no idea how to use it :-) Let me know when there's such information...

**Comment by CAMOBAP** [comment]
@ronaldtse good point I did it for `site-gen` https://github.com/actions-mn/site-gen but missed this one 
Will update README soon

**Comment by CAMOBAP** [comment]
@ronaldtse could you please have a look at updated README https://github.com/actions-mn/build-and-publish/blob/main/README.md

If it is good, I will propagate it to other repos (and update metanorma.com)

**Comment by ronaldtse** [comment]
@CAMOBAP there are a few typos there. Can you add 2 complete examples (for Docker, then Ubuntu), so that a user can just copy and paste?

**Comment by CAMOBAP** [comment]
Done

**Comment by ronaldtse** [comment]
@CAMOBAP can you also help provide an example in README for these cases?

1. Using Metanorma in private repository (e.g. https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2)
2. Using a private metanorma flavor (e.g. bsi/nist)

Thanks!
