### ISSUE TITLE
Action should also work for private repositories

### ISSUE THREAD

**Issue by ronaldtse** [actions-mn/build-and-publish#5]
In GitHub, private repositories do not have the GitHub Pages feature unless under the Enterprise package.

This means that for private repositories this action will fail, because the `actions/configure-pages` action will fail:
https://github.com/actions-mn/build-and-publish/blob/d6dab6f41eb92357b20b7083b6643cf2bc54bd80/action.yml#L35

Instead, we can support the conditional if for a composite action:
* https://github.com/actions/runner/issues/834
* Docs: https://github.com/github/docs/pull/12378/files

This workflow should just upload artifact if the pages is not available.

We will need to insert a CLI option to detect whether the repository has Pages enabled, like this:

Output for private repository (even when authenticated):
```sh
$ gh api   -H "Accept: application/vnd.github+json"   -H "X-GitHub-Api-Version: 2022-11-28"   /repos/metanorma/mn-samples-bsi/pages
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/pages#get-a-github-pages-site"
}
gh: Not Found (HTTP 404)
```

Output for public repository (with Pages enabled):
```sh
gh api   -H "Accept: application/vnd.github+json"   -H "X-GitHub-Api-Version: 2022-11-28"   /repos/metanorma/mn-samples-iho/pages
{
  "url": "https://api.github.com/repos/metanorma/mn-samples-iho/pages",
  "status": "built",
  "cname": null,
  "custom_404": false,
  "html_url": "https://metanorma.github.io/mn-samples-iho/",
  "build_type": "legacy",
  "source": {
    "branch": "gh-pages",
    "path": "/"
  },
  "public": true,
  "protected_domain_state": null,
  "pending_domain_unverified_at": null,
  "https_enforced": true
}
```

So if we get a 404, it means there is no Pages. Then we do not run the `actions/configure-pages` action, but only run `upload-artifact`.

**Comment by ronaldtse** [comment]
From @CAMOBAP :

* for private repos just upload artifact
* for public repo continue actions/upload-pages-artifact@v1

Also I think it make sense to "force" upload artifact to use this action with [deploy-pr-preview](https://github.com/marketplace/actions/deploy-pr-preview)

**Comment by ronaldtse** [comment]
@CAMOBAP when this is done, please help update the workflow in this repo, thanks!
* https://github.com/metanorma/iso-15926-6

**Comment by CAMOBAP** [comment]
Done
