### ISSUE TITLE
(URGENT) Repository with GitHub Pages enabled not using the correct artifact name

### ISSUE THREAD

**Issue by ronaldtse** [actions-mn/build-and-publish#9]
Reported by @hasel001 from @iho-ohi:
⁠
https://github.com/iho-ohi/S-102-Product-Specification/actions/runs/4918504824

is not deploying.

The deployment step is failing:

<img width="928" alt="Screenshot 2023-05-10 at 6 02 28 PM" src="https://github.com/actions-mn/build-and-publish/assets/11865/5fddbc92-006a-4b57-813a-fbbe6b9f8a8d">

Because the build step "thinks" that GitHub Pages is not enabled, and generates with an artifact name other than "github-pages"

<img width="921" alt="Screenshot 2023-05-10 at 6 03 09 PM" src="https://github.com/actions-mn/build-and-publish/assets/11865/df89ff55-7ac9-443f-a67b-cf9648a901ee">
...
<img width="590" alt="Screenshot 2023-05-10 at 6 03 31 PM" src="https://github.com/actions-mn/build-and-publish/assets/11865/5f6f2349-05df-4bb1-883d-49684f27d463">

Notice at the end it says "metanorma-build-artifact".

However, this repository has "GitHub Pages" enabled as source:
<img width="1167" alt="Screenshot 2023-05-10 at 6 04 18 PM" src="https://github.com/actions-mn/build-and-publish/assets/11865/8308e7d7-74c7-4384-9b41-8a46dd35f964">

**Comment by CAMOBAP** [comment]
@ronaldtse quick solution for this is to add token: ${{ secrets.GITHUB_TOKEN }}. I have prepared PR https://github.com/iho-ohi/S-102-Product-Specification/pull/42

### Details

`build-and-publish` action is trying to check on its own if GitHub pages are enabled or not. To do this check we run `gh api ...` command which requires token

---

I will make this input as required so we will not miss it.

And maybe better we should provide additional input 'deliverable' with possible values:
 - auto
 - artifact-upload
 - github-pages

@ronaldtse how do you think?

**Comment by CAMOBAP** [comment]
> However, why is the explicit token needed?

Because `gh` cli requires it https://cli.github.com/manual/gh_auth_login

> Can’t it be part of the workflow?

Unfortunatelly all secrets have to be passed explicitly to actions/sub-workflows due to security reasons

> Or use the new permissions key for a token that can write to pages?

It's not about pages permissions, it's just about accessing GitHub API via `gh` command line tool

**Comment by ronaldtse** [comment]
Got it, thank you @CAMOBAP . Can you document this reason in the README of the repository? Thanks!
